[test]
levels = ["syntax", "javascript", "install", "registration", "instantiation", "execution"]

[test.workflows]
cpu = "all"
cuda = "all"

[test.platforms]
platforms = ["linux", "macos", "windows", "windows_portable", "linux_cuda", "windows_cuda", "windows_portable_cuda"]